language: node_js
node_js:
  - 4.3

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager update
  - nohup bash -c "webdriver-manager start 2>&1 &"
  - sleep 3

script:
  - node_modules/.bin/karma start test/karma.conf.js --single-run
  - node_modules/.bin/protractor test/protractor.conf.js